AWS_REGION = "us-west-2"

DEFAULT_SQS_IN  = "LOADBALANCE_IN"
DEFAULT_SQS_OUT = "LOADBALANCE_OUT"

DEFAULT_BASE_PORT       = 7777
DEFAULT_SUBSCRIBE_TO    = "localhost"
DEFAULT_WRITE_CAPACITY  = 10
DEFAULT_READ_CAPACITY   = 10
